buildscript {
    repositories {
        mavenLocal()
        mavenCentral { url 'https://maven.aliyun.com/repository/central' }
    }

    dependencies {
    }
}

allprojects {
    repositories {
        mavenLocal()
        mavenCentral { url 'https://maven.aliyun.com/repository/central' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}